name: E2E Tests on Render Deploy Branch

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [render_deploy_succeeded]
  push:
    branches:
      - deploy/render-staging

jobs:
  e2e-smoke:
    name: Smoke (Render URL)
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-focal
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx playwright install --with-deps chromium

      - name: Wait for Render health
        env:
          BASE_URL: https://cricket-academy-app.onrender.com
        run: |
          for i in {1..24}; do \
            echo "Health check $i"; \
            if curl -fsS "$BASE_URL/api/ping" >/dev/null; then echo OK; exit 0; fi; \
            sleep 5; \
          done; \
          echo "Service not healthy"; exit 1

      - name: Run smoke tests
        env:
          BASE_URL: https://cricket-academy-app.onrender.com
          ADMIN_EMAIL: admin@test.com
          ADMIN_PASSWORD: password
        run: |
          npx playwright test tests/smoke.login-api.spec.ts --reporter=list || true

      - name: Upload smoke artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-smoke-results
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore

  e2e-render:
    name: Full E2E (Render URL)
    needs: e2e-smoke
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-focal
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx playwright install --with-deps chromium

      - name: Run full E2E
        env:
          BASE_URL: https://cricket-academy-app.onrender.com
          ADMIN_EMAIL: admin@test.com
          ADMIN_PASSWORD: password
        run: |
          npx playwright test --reporter=list || true

      - name: Upload E2E artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-e2e-results
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore

name: E2E Tests on Render Deploy Branch

on:
  push:
    branches:
      - deploy/render-staging
  workflow_dispatch:

jobs:
  e2e-render:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Wait for Render deployment
        run: |
          echo "⏳ Waiting for Render deployment at https://cricket-academy-app.onrender.com"
          npx wait-on -t 300000 "https://cricket-academy-app.onrender.com/api/_debug/echo" || true
      
      - name: Run E2E tests against live Render deployment
        env:
          BASE_URL: https://cricket-academy-app.onrender.com
          ENABLE_DEV_LOGIN: true
        run: |
          echo "🧪 Running E2E tests against production deployment"
          npx playwright test tests/basic.smoke.spec.ts tests/e2e/smoke.login.spec.ts \
            --reporter=list,html \
            --project="Desktop Chrome" \
            || echo "Some tests failed, continuing..."
      
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-render
          path: playwright-report/
          retention-days: 7
      
      - name: Check test results
        if: failure()
        run: |
          echo "❌ E2E tests failed on Render deployment"
          echo "Check the uploaded Playwright report for details"
          exit 1

