name: E2E Tests

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [render_deployed]

jobs:
  e2e-local:
    name: E2E Tests (Local Build)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Build application
        run: npm run build
      
      - name: Setup test database
        run: |
          # Use SQLite for CI tests
          touch dev.db
        env:
          DATABASE_URL: file:./dev.db
      
      - name: Run E2E tests (local)
        run: npm run test:e2e
        env:
          CI: true
          RUN_LOCAL_WEB: '1'
          BASE_URL: http://localhost:10000
          DATABASE_URL: file:./dev.db
          SESSION_SECRET: test-secret-ci
          JWT_ACCESS_SECRET: test-jwt-secret-ci
          NODE_ENV: development
      
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-local
          path: playwright-report/
          retention-days: 7

  e2e-render:
    name: E2E Tests (Render Deployment)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Wait for Render deployment
        run: npx wait-on https://legacy-cricket-app.onrender.com/healthz --timeout 180000 --interval 5000 || echo "Health check timed out, continuing anyway..."
      
      - name: Run E2E tests (Render)
        run: npm run test:e2e:render
        env:
          CI: true
          BASE_URL: https://legacy-cricket-app.onrender.com
      
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-render
          path: playwright-report/
          retention-days: 7

